- hosts: cs-checker
  tasks:

    - name: thinkerer build
      connection: local
      shell: chdir=../checkers/thinkerer ./get_checker.sh

    - name: sync catalog
      synchronize: src="../checkers" dest="{{cs_dir}}"

    - name: checker owner
      file:
        path:  "{{cs_dir}}/checkers"
        owner: "{{cs_user}}"
        group: "{{cs_user}}"
        recurse: yes

    - name: install sys deps
      apt: name=python3-pip state=latest

    - name: python deps
      pip: name={{item}} executable=pip3
      with_items:
        - requests
        - ws4py
        - mimesis
        - Faker
        - beautifulsoup4
        - pycryptodome
        - aiohttp
