- name: enable and restart services
  systemd: name={{ item }} enabled=yes state=restarted daemon_reload=yes
  with_items:
    - index

- name: enable and restart mongo
  systemd: name=mongod enabled=yes state=restarted daemon_reload=yes
