- hostname:
    name: brainhugger

# put your authorized key here
#- name: Set authorized key
#  authorized_key:
#    user: root
#    key: "ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx name@domain"
#    state: present
    
- name: Set authorized key
  authorized_key:
    user: root
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChwnWi6oZBqJqT11cXHSi/WWtC2pr68klcxhwMD/ZoRR50X7g1trZWronYwqNg2FcVirl35kbPZj+9a8CZmwg/DpJOnlorKFccII4qSLKqp9t+P8rDlNXoppz8hq3juVtA0JDRCiAOF+04tSvMDf/vzA02WaWV6813o4+JL+Jee0oNvNCscj/qmdAZ7k1+XR/0ZazgQeB88YpkEmYm6F9+kWutCAvFU6zV6LzfiQ9DWFFcDac4OXirI61yyaIHKxnk0ltYQCD/1YDglp5BUupJaLHPw4Qz/2GUFWgWc/ZzbEDyUKdsL4NSyw+agAfNovn59SlUbTtrJAH/hr2f34KF werelaxe@Billy"
    state: present
    
- name: create user
  user: name=brainhugger shell=/bin/false

- name: copy motd
  copy: src=motd dest=/etc/motd

# example of installing packages
#- name: install packages
#  apt: 
#    #update_cache: yes
#    name:
#      - cowsay  
  
- name: copy service
  copy: src="brainhugger.py" dest=/home/brainhugger/
  notify: enable and restart services

# example of reusing the files from services folder
#- name: copy service
#  copy: src="{{ playbook_dir }}/../services/brainhugger/brainhugger.py" dest=/home/brainhugger/
#  notify: enable and restart services

# example of copying dirs with many files
#- name: copy service files
#  synchronize: 
#    src: "{{ playbook_dir }}/../services/brainhugger/"
#    dest: /home/brainhugger/
#    rsync_opts:
#      - "--chmod=D0770"
#      - "--chmod=F0660"
#      - "--chown=brainhugger:brainhugger"
#  notify: enable and restart services
#

- name: fix permissions
  file: name=/home/brainhugger owner=brainhugger group=brainhugger recurse=yes state=directory

- name: make service executable
  file: path={{item}} mode=0755
  with_items:
    - /home/brainhugger/brainhugger.py
  notify: enable and restart services

- name: add service files
  copy: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  notify: enable and restart services
  with_items:
    - brainhugger

