- hostname:
    name: brainhugger

- name: Set authorized key
  authorized_key:
    user: root
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChwnWi6oZBqJqT11cXHSi/WWtC2pr68klcxhwMD/ZoRR50X7g1trZWronYwqNg2FcVirl35kbPZj+9a8CZmwg/DpJOnlorKFccII4qSLKqp9t+P8rDlNXoppz8hq3juVtA0JDRCiAOF+04tSvMDf/vzA02WaWV6813o4+JL+Jee0oNvNCscj/qmdAZ7k1+XR/0ZazgQeB88YpkEmYm6F9+kWutCAvFU6zV6LzfiQ9DWFFcDac4OXirI61yyaIHKxnk0ltYQCD/1YDglp5BUupJaLHPw4Qz/2GUFWgWc/ZzbEDyUKdsL4NSyw+agAfNovn59SlUbTtrJAH/hr2f34KF werelaxe@Billy"
    state: present
    
- name: create user
  user: name=brainhugger shell=/bin/false

- name: copy motd
  copy: src=motd dest=/etc/motd

- name: install packages
  apt:
    update_cache: yes
    name:
      - golang-go

- name: set GOPATH
  copy: src=go-path.sh
        dest=/etc/profile.d

- name: create service directory
  file:
    path: /home/brainhugger/go/src
    state: directory

- name: copy service files
  synchronize:
    src: "{{ playbook_dir }}/../services/brainhugger/"
    dest: /home/brainhugger/go/src/brainhugger
    rsync_opts:
      - "--chmod=D0770"
      - "--chown=brainhugger:brainhugger"
      - "--exclude=bhexecutor.notc"
  notify: enable and restart services

- name: fix permissions
  file: name=/home/brainhugger/go/src/brainhugger owner=brainhugger group=brainhugger recurse=yes state=directory

- name: add service files
  copy: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  notify: enable and restart services
  with_items:
    - brainhugger

