- hostname:
    name: brainhugger

- name: create user
  user: name=brainhugger shell=/bin/false

- name: copy motd
  copy: src=motd dest=/etc/motd

# example of installing packages
#- name: install packages
#  apt: 
#    #update_cache: yes
#    name:
#      - cowsay  
  
- name: copy service
  copy: src="brainhugger.py" dest=/home/brainhugger/
  notify: enable and restart services

# example of reusing the files from services folder
#- name: copy service
#  copy: src="{{ playbook_dir }}/../services/brainhugger/brainhugger.py" dest=/home/brainhugger/
#  notify: enable and restart services

# example of copying dirs with many files
#- name: copy service files
#  synchronize: 
#    src: "{{ playbook_dir }}/../services/brainhugger/"
#    dest: /home/brainhugger/
#    rsync_opts:
#      - "--chmod=D0770"
#      - "--chmod=F0660"
#      - "--chown=brainhugger:brainhugger"
#  notify: enable and restart services
#

- name: fix permissions
  file: name=/home/brainhugger owner=brainhugger group=brainhugger recurse=yes state=directory

- name: make service executable
  file: path={{item}} mode=0755
  with_items:
    - /home/brainhugger/brainhugger.py
  notify: enable and restart services

- name: add service files
  copy: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  notify: enable and restart services
  with_items:
    - brainhugger

