- hostname:
    name: beacons

# put your authorized key here
#- name: Set authorized key
#  authorized_key:
#    user: root
#    key: "ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx name@domain"
#    state: present
    
- name: create user
  user: name=beacons shell=/bin/false

- name: create mongo user
  user: name=mongodb shell=/bin/false create_home=false

- name: copy motd
  copy: src=motd dest=/etc/motd

- name: unpack mongo bins
  unarchive:
    src: mongo_bins.tar.gz
    dest: /usr/bin/
  notify: enable and restart mongo

- name: copy mongo config
  copy: src="mongod.conf" dest=/etc/
  notify: enable and restart mongo

- name: copy mongod.service
  copy: src="mongod.service" dest=/etc/systemd/system
  notify: enable and restart mongo

- name: create mongo logs dir
  file:
    path: /var/mongo
    state: directory
    owner: mongodb
    group: mongodb
  notify: enable and restart mongo

- name: create mongo data dir
  file:
    path: /var/lib/mongodb
    state: directory
    owner: mongodb
    group: mongodb
  notify: enable and restart mongo

- name: install packages
  apt: 
    update_cache: yes
    name:
      - python3.6-dev
      - python3-pip
      - python-setuptools
      - python3-setuptools
      - python3-pymongo
      - python3-motor
      - python3-jinja2
      - python3-uvloop

- name: copy service files
  synchronize: 
    src: "{{ playbook_dir }}/../services/beacons/"
    dest: /home/beacons/
    rsync_opts:
      - "--chmod=D0770"
      - "--chmod=F0660"
      - "--chown=beacons:beacons"
  notify: enable and restart services

- pip:
    requirements: /home/beacons/requirements.txt
    executable: pip3


- name: fix permissions
  file: name=/home/beacons owner=beacons group=beacons recurse=yes state=directory

- name: make service executable
  file: path={{item}} mode=0755
  with_items:
    - /home/beacons/main.py
    - /home/beacons/data_cleaner.py
  notify: enable and restart services

- name: add service files
  copy: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  notify: enable and restart services
  with_items:
    - beacons
    - beacons-datacleaner

