- hostname:
    name: beacons

- name: create user
  user: name=beacons shell=/bin/false

- name: copy motd
  copy: src=motd dest=/etc/motd

# example of installing packages
#- name: install packages
#  apt: 
#    #update_cache: yes
#    name:
#      - cowsay

- name: copy service
  copy: src="beacons.py" dest=/home/beacons/
  notify: enable and restart services

# example of reusing the files from services folder
#- name: copy service
#  copy: src="{{ playbook_dir }}/../services/beacons/beacons.py" dest=/home/beacons/
#  notify: enable and restart services

# example of copying dirs with many files
#- name: copy service files
#  synchronize: 
#    src: "{{ playbook_dir }}/../services/beacons/"
#    dest: /home/beacons/
#    rsync_opts:
#      - "--chmod=D0770"
#      - "--chmod=F0660"
#      - "--chown=beacons:beacons"
#  notify: enable and restart services
#

- name: fix permissions
  file: name=/home/beacons owner=beacons group=beacons recurse=yes state=directory

- name: make service executable
  file: path={{item}} mode=0755
  with_items:
    - /home/beacons/beacons.py
  notify: enable and restart services

- name: add service files
  copy: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  notify: enable and restart services
  with_items:
    - beacons

