- hostname:
    name: sandbox

- name: create user
  user: name=sandbox shell=/bin/false

- name: copy motd
  copy: src=motd dest=/etc/motd

# example of installing packages
#- name: install packages
#  apt: 
#    #update_cache: yes
#    name:
#      - cowsay

- name: copy service
  copy: src="sandbox.py" dest=/home/sandbox/
  notify: enable and restart services

# example of reusing the files from services folder
#- name: copy service
#  copy: src="{{ playbook_dir }}/../services/sandbox/sandbox.py" dest=/home/sandbox/
#  notify: enable and restart services

# example of copying dirs with many files
#- name: copy service files
#  synchronize: 
#    src: "{{ playbook_dir }}/../services/sandbox/"
#    dest: /home/sandbox/
#    rsync_opts:
#      - "--chmod=D0770"
#      - "--chmod=F0660"
#      - "--chown=sandbox:sandbox"
#  notify: enable and restart services
#

- name: fix permissions
  file: name=/home/sandbox owner=sandbox group=sandbox recurse=yes state=directory

- name: make service executable
  file: path={{item}} mode=0755
  with_items:
    - /home/sandbox/sandbox.py
  notify: enable and restart services

- name: add service files
  copy: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  notify: enable and restart services
  with_items:
    - sandbox

