- hostname:
    name: sandbox

# put your authorized key here
#- name: Set authorized key
#  authorized_key:
#    user: root
#    key: "ssh-rsa xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx name@domain"
#    state: present

- name: copy motd
  copy: src=motd dest=/etc/motd

# example of installing packages
#- name: install packages
#  apt: 
#    #update_cache: yes
#    name:
#      - cowsay

- name: create autostart dir
  file: 
    path: /home/user/.config/autostart/
    state: directory
    owner: user
    group: user

# example of reusing the files from services folder
- name: copy autostart config
  copy: src="sandbox.desktop" dest=/home/user/.config/autostart/sandbox.desktop owner=user group=user
  notify: enable and restart services

# example of copying dirs with many files
- name: copy service files
  synchronize: 
    src: "{{ playbook_dir }}/../services/sandbox/"
    dest: /home/user/sandbox/
    rsync_opts:
      - "--chmod=D0770"
      - "--chmod=F0660"
      - "--chown=user:user"
      - "--exclude=proxy/interface.cpp"
      - "--exclude=build_so.sh"
  notify: enable and restart services

- name: fix permissions
  file: name=/home/user/sandbox owner=user group=user recurse=yes state=directory
  file: name=/home/user/sandbox/static owner=nginx group=nginx recurse=yes state=directory

- name: build sandbox executable
  command: make -j8
  args:
    chdir: /home/user/sandbox/sandbox
    creates: /home/user/sandbox/sandbox/sandbox

- name: build proxy executable
  command: make
  args:
    chdir: /home/user/sandbox/proxy
    creates: /home/user/sandbox/proxy/proxy

- name: build proxy docker image
  command: docker build --tag=proxy /home/user/sandbox/proxy

- name: start proxy container
  docker_container:
    name: proxy
    image: proxy
    network_mode: host
    restart: yes
    restart_policy: on-failure

- name: build proxy_v2 docker image
  command: docker build --tag=proxy_v2 /home/user/sandbox/proxy_v2

- name: start proxy_v2 container
  docker_container:
    name: proxy_v2
    image: proxy_v2
    network_mode: host
    restart: yes
    restart_policy: on-failure

- name: copy nginx config
  copy: src=default dest=/etc/nginx/sites-available/default
  notify: enable and restart services

